### ISSUE TITLE
response header without content-type header

### ISSUE THREAD

**Issue by KaseiHaku** [reifiedbeans/vite-plugin-serve-static#13]
when encounter unrecognized file type, return ''application/octet-stream'' for the content-type response header maybe a better choice.
when i request a static assets with URL 'http://domain:port/path/to/filename.vue',
the browser report an error for this case
`"Content-Type": type || 'application/octet-stream',`
maybe is better than 
`"Content-Type": type || undefined,`
in the file [middleware.ts](https://github.com/reifiedbeans/vite-plugin-serve-static/blob/main/lib/middleware.ts)
or add new config option with this case

**Comment by reifiedbeans** [comment]
Hey @KaseiHaku, thanks for reporting this issue. Looking into this, your recommendation of using `application/octet-stream` seems to be the best path forward. The `mime-types` library that this plugin uses [says something to a similar effect](https://github.com/jshttp/mime-types#readme):

> **No fallbacks.** Instead of naively returning the first available type, `mime-types` simply returns `false`, so do `var type = mime.lookup('unrecognized') || 'application/octet-stream'`.

That being said, I want to provide an escape hatch of sorts in case folks want to use a different content type. I'll start looking into adding new config options to control this behavior.

**Comment by reifiedbeans** [comment]
Could you also provide the error that the browser is showing?

**Comment by reifiedbeans** [comment]
I wasn't able to replicate your error, but I'm seeing a different one:

> Internal server error: Invalid value "undefined" for header "Content-Type"

This is looking more like a bug than an enhancement. I'll switch the default content type to `application/octet-stream` in a patch version while I think about how we might handle configuring it.

Feel free to re-test once that patch is out, then we can see if there is another issue with the content length.

**Comment by KaseiHaku** [comment]
thank you for repair so fast,  re-test is unnecessary, because before i post the issue, i modify the default Content-Type in node_modules/vite-plugin-serve-static/dist/index.js to make it work properly
