### ISSUE TITLE
Getting CORS error

### ISSUE THREAD

**Issue by kennetng** [reifiedbeans/vite-plugin-serve-static#3]
Hi! 
Could we make it possible to configure custom headers or use vite.server.cors setting when serving files? I could try to make a PR for this feature, but I am pretty new to open source.

**Comment by reifiedbeans** [comment]
Hey @kennetng, thanks for opening this issue. Can you provide more information on the CORS error you are getting and what your use case is?

The main intent of this plugin is to serve files from the same address as the bundle coming from Vite, so I am a bit confused on where CORS comes into play here.

**Comment by reifiedbeans** [comment]
I've been able to reproduce _some_ CORS error.

**vite.config.ts**
```ts
import { defineConfig } from "vite";
import serveStatic from "vite-plugin-serve-static";

export default defineConfig({
    plugins: [
        serveStatic([
            {
                pattern: /^\/test/,
                resolve: './test.txt',
            },
        ]),
    ],
    server: {
        cors: true,
    },
});
```

**index.html**
```html
<!DOCTYPE html>
<html>
    <script>
        async function getTest() {
            const res = await fetch('http://localhost:5173/test');
            console.log(res);
        }
        void getTest();
    </script>
</html>
```

----

Serving `index.html` from a different host results in the following error:

> Access to fetch at 'http://localhost:5173/test' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

----

I'm not exactly sure why the CORS config from Vite isn't being inherited here. I suspect it has to do something about the ordering of the middleware.

**Comment by reifiedbeans** [comment]
Should have done a bit more research...seems this is trivially possible with Vite.

> The configureServer hook is called before internal middlewares are installed, so the custom middlewares will run before internal middlewares by default. If you want to inject a middleware after internal middlewares, you can return a function from configureServer, which will be called after internal middlewares are installed

https://vitejs.dev/guide/api-plugin.html#configureserver

----

I'll whip up a quick CR for this and get it published soon. Thanks for bringing this to my attention!

**Comment by kennetng** [comment]
Wow! Thanks for the quick feature. 
I'm working on a micro-frontend framework that needs to serve JS and CSS bundles to the main App-Shell. I try to avoid using a BFF for it, but this solves my issue hopefully 🙌
